clc;
clear;
close all;
M =1;
N=100;
nsample=4;
fc=1;dt=1/fc/nsample;
t=0:dt:N-dt;
s=sign(randn(1,N));
d=zeros(fc*nsample,length((s+1)/2));
d(1,:)=s;
d=reshape(d,1,fc*nsample*length((s+1)/2));
g=ones(1,fc*nsample);dd=conv(d,g);
sfsk=2*dd-1;
fsk=cos(2*pi*fc*t+2*pi*sfsk(1:length(t)).*t);
sfft=abs(fft(fsk));
sfft=sfft.^2/length(sfft);
subplot(121);
plot(1:200, fsk(1:200));
title('2FSK时域波形');
subplot(122);
plot(sfft);
title('2FSK功率谱图');
